create table person (
	person_Id int generated by default as identity primary key,
	login varchar(20),
	name varchar(20),
	surname varchar(20),
	date_of_birth date,
	email varchar(40),
	balance decimal,
	password varchar(64),
	role int,
	status bool,
	foreign key (role) references person_role (person_role_id)
);
create table person_role (
	person_role_id int generated by default as identity primary key,
	person_role_name varchar(20)
);
create table bike (
	bike_id int generated by default as identity primary key,
	serial_number varchar(10),
	status varchar(30)
);
create table parking_point (
	parking_point_id int generated by default as identity primary key,
	name varchar(20),
	address varchar(40)
);
create table parking_point_bike_map (
	parking_point_bike_map_id int generated by default as identity primary key,
	bike int,
	parking_point int,
	foreign key (bike) references bike (bike_id),
	foreign key (parking_point) references parking_point (parking_point_id)
);
create table "order" (
	order_id int generated by default as identity primary key,
	date_of_begin timestamp,
	term integer,
	end_date timestamp,
	person int,
	bike int,
	parkingpoint int,
	status varchar(20),
	foreign key (person) references person (person_id),
	foreign key (bike) references bike (bike_id),
	foreign key (parking_point) references parking_point (parking_point_id)
);
